targets:
  ADRB2:
    receptor_mol2: LIT_PCBA/ADRB2/ADRB2_protein.mol2
    actives_smi: LIT_PCBA/ADRB2/actives.smi
    inactives_smi: LIT_PCBA/ADRB2/inactives.smi
    box_center:
      x: -1.8
      y: -13.1
      z: -50.9
  ALDH1:
    receptor_mol2: LIT_PCBA/ALDH1/ALDH1_protein.mol2
    actives_smi: LIT_PCBA/ALDH1/actives.smi
    inactives_smi: LIT_PCBA/ALDH1/inactives.smi
    box_center:
      x: 34.0
      y: -16.7
      z: 13.3
  ESR1_ant:
    receptor_mol2: LIT_PCBA/ESR1_ant/ESR1_ant_protein.mol2
    actives_smi: LIT_PCBA/ESR1_ant/actives.smi
    inactives_smi: LIT_PCBA/ESR1_ant/inactives.smi
    box_center:
      x: -2.1
      y: -30.9
      z: 21.8
  ESR1_ago:
    receptor_mol2: LIT_PCBA/ESR1_ago/ESR1_ago_protein.mol2
    actives_smi: LIT_PCBA/ESR1_ago/actives.smi
    inactives_smi: LIT_PCBA/ESR1_ago/inactives.smi
    box_center:
      x: 3.9
      y: 4.8
      z: -6.2
  FEN1:
    receptor_mol2: LIT_PCBA/FEN1/FEN1_protein.mol2
    actives_smi: LIT_PCBA/FEN1/actives.smi
    inactives_smi: LIT_PCBA/FEN1/inactives.smi
    box_center:
      x: -17.4
      y: -5.1
      z: 1.4
  GBA:
    receptor_mol2: LIT_PCBA/GBA/GBA_protein.mol2
    actives_smi: LIT_PCBA/GBA/actives.smi
    inactives_smi: LIT_PCBA/GBA/inactives.smi
    box_center:
      x: 32.9
      y: 34.7
      z: -19.3
  IDH1:
    receptor_mol2: LIT_PCBA/IDH1/IDH1_protein.mol2
    actives_smi: LIT_PCBA/IDH1/actives.smi
    inactives_smi: LIT_PCBA/IDH1/inactives.smi
    box_center:
      x: 12.11
      y: 28.09
      z: 80.47
  KAT2A:
    receptor_mol2: LIT_PCBA/KAT2A/KAT2A_protein.mol2
    actives_smi: LIT_PCBA/KAT2A/actives.smi
    inactives_smi: LIT_PCBA/KAT2A/inactives.smi
    box_center:
      x: -15.9
      y: -6.6
      z: 13.1
  MAPK1:
    receptor_mol2: LIT_PCBA/MAPK1/MAPK1_protein.mol2
    actives_smi: LIT_PCBA/MAPK1/actives.smi
    inactives_smi: LIT_PCBA/MAPK1/inactives.smi
    box_center:
      x: -15.2
      y: 14.1
      z: 42.9
  MTORC1:
    receptor_mol2: LIT_PCBA/MTORC1/MTORC1_protein.mol2
    actives_smi: LIT_PCBA/MTORC1/actives.smi
    inactives_smi: LIT_PCBA/MTORC1/inactives.smi
    box_center:
      x: 35.5
      y: 48.6
      z: 35.3
  OPRK1:
    receptor_mol2: LIT_PCBA/OPRK1/OPRK1_protein.mol2
    actives_smi: LIT_PCBA/OPRK1/actives.smi
    inactives_smi: LIT_PCBA/OPRK1/inactives.smi
    box_center:
      x: 60.3
      y: -24.6
      z: -4.1
  PKM2:
    receptor_mol2: LIT_PCBA/PKM2/PKM2_protein.mol2
    actives_smi: LIT_PCBA/PKM2/actives.smi
    inactives_smi: LIT_PCBA/PKM2/inactives.smi
    box_center:
      x: 10.9
      y: 3.1
      z: 13.6
  PPARG:
    receptor_mol2: LIT_PCBA/PPARG/PPARG_protein.mol2
    actives_smi: LIT_PCBA/PPARG/actives.smi
    inactives_smi: LIT_PCBA/PPARG/inactives.smi
    box_center:
      x: 11.7
      y: 49.0
      z: 61.2
  TP53:
    receptor_mol2: LIT_PCBA/TP53/TP53_protein.mol2
    actives_smi: LIT_PCBA/TP53/actives.smi
    inactives_smi: LIT_PCBA/TP53/inactives.smi
    box_center:
      x: 91.9
      y: 94.1
      z: -45.7
  VDR:
    receptor_mol2: LIT_PCBA/VDR/VDR_protein.mol2
    actives_smi: LIT_PCBA/VDR/actives.smi
    inactives_smi: LIT_PCBA/VDR/inactives.smi
    box_center:
      x: 10.7
      y: -4.1
      z: -32.2
